name: CI/CD Docker Pipeline for Streamlit App

# Run this workflow on every push to the main branch
on:
  push:
    branches:
      - master

# Define the jobs that will be run
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Set up Docker on the machine
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    # Step 3: Log in to Docker Hub (You need to set up secrets for DOCKER_USERNAME and DOCKER_PASSWORD in your repo settings)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Step 4: Build the Docker image
    - name: Build Docker image
      run: docker build -f DockerFile . -t ${{ secrets.DOCKER_USERNAME }}/ipl-predictor:latest    
    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ipl-predictor:latest
    
    # Optional: Step 6: Run tests (e.g., test the app runs)
    - name: Run the container
      run: docker run -d -p 8501:8501 --name ipl-predictor ${{ secrets.DOCKER_USERNAME }}/ipl-predictor:latest
    
    - name: Test the Streamlit app
      run: curl http://localhost:8501
    
    # Clean up the container
    - name: Stop and remove container
      run: |
        docker stop ipl-predictor
        docker rm ipl-predictor
